name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update db url
      run: sed -i 's/<db_url>/${{ secrets.DB_URL }}/' src/main/resources/apllication.properties

    - name: update db user
      run: sed -i 's/<db_user>/${{ secrets.DB_USER }}/' src/main/resources/apllication.properties

    - name: update db pass
      run: sed -i 's/<db_pass>/${{ secrets.DB_PASS }}/' src/main/resources/apllication.properties

    - name: update google client id
      run: sed -i 's/<google_id>/${{ secrets.GOOGLE_CLIENT_ID }}/' src/main/resources/apllication.properties

    - name: update google secret
      run: sed -i 's/<google_secret>/${{ secrets.GOOGLE_CLIENT_SECRET }}/' src/main/resources/apllication.properties
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ vars.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: skeffy/octave:latest
